spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: false
    show-sql: true
  flyway:
    enabled: false


auth:
  secret: Y21jMTF0aGFub3RoZXJjbWNzdXJmbWF0ZWNtYzExdGhhbm90aGVyY21jc3VyZm1hdGUfwegwegewfwwgwegwggsfgergtrr
  tokenValidation: 1000


logging:
  level:
    org.hibernate.sql: debug